---
- hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Check running config on interface before change
      cisco.ios.ios_config:
        lines: show running-config interface GigabitEthernet0/1

    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
        - name: GigabitEthernet0/1
          ipv4:
          - address: 192.168.0.1/24

    - name: Check running config on interface after change
      cisco.ios.ios_config:
        lines: show run interface GigabitEthernet0/1

    - name: check the startup-config against the running-config
      cisco.ios.ios_config:
        diff_against: startup
        diff_ignore_lines:
        - ntp clock .*