---
- hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
        - name: GigabitEthernet0/2
          ipv4:
          - address: 192.168.1.1/24

    - name: check the running-config against master config
      cisco.ios.ios_config:
        diff_against: running